In [1]:
salary=[1000,1500,1200,2000]
bs=[50,60,55,70]

In [3]:
total=salary+bs
total

[1000, 1500, 1200, 2000, 50, 60, 55, 70]

In [5]:
import numpy as np

In [8]:
salary_array=np.array(salary)
bs_array=np.array(bs)
print(salary_array)
print(bs_array)

[1000 1500 1200 2000]
[50 60 55 70]


In [9]:
total=salary_array+bs_array
total

array([1050, 1560, 1255, 2070])

### single data type

In [11]:
np.array([1, 2 ,3 ,5.5])

array([1. , 2. , 3. , 5.5])

In [16]:
np.array([1, 2 ,3 ,5.5,"m"])

array(['1', '2', '3', '5.5', 'm'], dtype='<U32')

In [18]:
np.array([1, 2 ,3 ,True])

array([1, 2, 3, 1])

In [19]:
np.array([1, 2 ,3 ,True,"m"])

array(['1', '2', '3', 'True', 'm'], dtype='<U11')

### 1D Array as a column

In [14]:
np.array([1, 2 ,3 ,5])

array([1, 2, 3, 5])

### 2D Array as a table

In [15]:
np.array([[1, 2 ],[3 ,5.5]])

array([[1. , 2. ],
       [3. , 5.5]])

### Array Attr.

### ndim  --> return the dim of the array

In [22]:
a=np.array([1, 2 ,3 ,5])
a

array([1, 2, 3, 5])

In [24]:
a.ndim

1

In [26]:
b=np.array([[1, 2 ],[3 ,5.5]])
b

array([[1. , 2. ],
       [3. , 5.5]])

In [27]:
b.ndim

2

### shape --> return the number of rows and columns in the array

In [28]:
a=np.array([1, 2 ,3 ,5])
a

array([1, 2, 3, 5])

In [29]:
a.shape

(4,)

In [30]:
b=np.array([[1, 2 ],[3 ,5.5]])
b

array([[1. , 2. ],
       [3. , 5.5]])

In [31]:
b.shape

(2, 2)

### size --> total number of items inside the array

In [32]:
a=np.array([1, 2 ,3 ,5])
a.size

4

In [34]:
b=np.array([[1, 2 ,3],[3 ,5.5,5]])
b.size

6

### dtype --> return the data type of the items inside the array

In [35]:
a.dtype

dtype('int32')

In [36]:
b.dtype

dtype('float64')

### ex.

In [38]:
x=[[180,78.4],
  [215,102.5],
  [210,98.3],
  [188,75.2]]

# import numpy
import numpy as np
# create 2D numpy array from x list with name (arry)
arry=np.array(x)
print(arry)
# print the type of the aray values
print(arry.dtype)
# print the shape of the array
print(arry.shape)

[[180.   78.4]
 [215.  102.5]
 [210.   98.3]
 [188.   75.2]]
float64
(4, 2)


### Creating an array using a function

In [40]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### arange()

In [44]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

### zeros()

In [48]:
np.zeros(7) # 7 is the shape (7 rows)

array([0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((7,2)) # 7 is the shape (7 rows)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### ones()

In [50]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.ones((7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### eye() --> identity matrix

In [53]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### random.rand() --> number between (0 & 1)

In [62]:
np.random.rand(10)

array([0.39849114, 0.01678182, 0.04448563, 0.04998606, 0.4737432 ,
       0.75889053, 0.78975593, 0.22356419, 0.71375944, 0.94662428])

In [67]:
np.random.rand(4,5)

array([[0.97456141, 0.29606338, 0.97916143, 0.3681012 , 0.0327496 ],
       [0.76448768, 0.53462588, 0.65848681, 0.28937284, 0.76730711],
       [0.44389146, 0.03979072, 0.12919578, 0.39440052, 0.16522305],
       [0.42759351, 0.27223128, 0.06941771, 0.93559744, 0.51289415]])

### random.randint()

In [96]:
np.random.randint(20,50)

28

### generating 10 random num

In [100]:
np.random.randint(20,50,(10))

array([35, 45, 20, 46, 28, 23, 47, 36, 38, 32])

### generating 20 random values with (4,5) shape

In [98]:
np.random.randint(20,50,(4,5))

array([[44, 36, 25, 36, 29],
       [47, 44, 41, 38, 28],
       [30, 45, 43, 21, 45],
       [42, 33, 30, 20, 22]])

### reshape()

In [117]:
a=np.random.randint(20,50,(4,5))
a

array([[34, 40, 34, 29, 48],
       [47, 46, 45, 28, 35],
       [33, 26, 41, 43, 42],
       [24, 40, 33, 34, 40]])

In [118]:
a.reshape(5,4)

array([[34, 40, 34, 29],
       [48, 47, 46, 45],
       [28, 35, 33, 26],
       [41, 43, 42, 24],
       [40, 33, 34, 40]])

### max , min

In [109]:
a=np.random.randint(10,50,10)
a

array([17, 15, 29, 20, 47, 33, 39, 33, 33, 27])

In [110]:
a.max()

47

In [111]:
a.min()

15

### use array index and slicing

### slicing for 1D Array

In [112]:
a=np.random.randint(10,50,10)
a

array([39, 47, 20, 42, 15, 35, 43, 32, 42, 32])

In [113]:
a[1]

47

In [114]:
a[1:5]

array([47, 20, 42, 15])

In [116]:
a[1::2]

array([47, 42, 35, 32, 32])

### slicing for 2D array

In [122]:
b=np.array([[34, 40, 34, 29, 48],
       [47, 46, 45, 28, 35],
       [33, 26, 41, 43, 42],
       [24, 40, 33, 34, 40]])
b

array([[34, 40, 34, 29, 48],
       [47, 46, 45, 28, 35],
       [33, 26, 41, 43, 42],
       [24, 40, 33, 34, 40]])

### slicing for single value

In [123]:
#40
b[0][1]

40

In [127]:
b[1][2]

45

### slicing for a row

In [128]:
[34, 40, 34, 29, 48]
b[0]

array([34, 40, 34, 29, 48])

### 2nd way to extract multiple values from a 2D array

In [133]:
# b[row index , colum index]
b[0:2,1:3]

array([[40, 34],
       [46, 45]])

In [135]:
#[[41, 43, 42],[33, 34, 40]]
b[2:,2:]

array([[41, 43, 42],
       [33, 34, 40]])

In [141]:
#[34,47,33,24]
b[:,0]

array([34, 47, 33, 24])

In [142]:
b[1,:]

array([47, 46, 45, 28, 35])

### slicing based on a condition

In [145]:
b=np.array([[14, 40, 34, 29, 48],
       [47, 46, 45, 28, 35],
       [13, 26, 61, 43, 82],
       [24, 40, 23, 34, 40]])

### get all values greater than 30 

In [146]:
b>30

array([[False,  True,  True, False,  True],
       [ True,  True,  True, False,  True],
       [False, False,  True,  True,  True],
       [False,  True, False,  True,  True]])

In [148]:
#b[condition]
b[b>30]

array([40, 34, 48, 47, 46, 45, 35, 61, 43, 82, 40, 34, 40])

In [150]:
b[b<40]

array([14, 34, 29, 28, 35, 13, 26, 24, 23, 34])

### logical operator (and- & ) (or- | )

In [159]:
#b<40 and b>30
b[(b<40) & (b>30)]

array([34, 35, 34])

In [160]:
#b>40 or b<30
b[(b>40) | (b<30)]

array([14, 29, 48, 47, 46, 45, 28, 13, 26, 61, 43, 82, 24, 23])

### Mathematical Operator

In [164]:
arr1=np.random.randint(10,100,(10))
arr1

array([54, 75, 51, 96, 71, 62, 24, 85, 42, 15])

In [165]:
arr2=np.random.randint(10,100,(10))
arr2

array([70, 17, 77, 30, 84, 35, 79, 12, 30, 15])

In [166]:
arr1+arr2

array([124,  92, 128, 126, 155,  97, 103,  97,  72,  30])

In [167]:
arr1-arr2

array([-16,  58, -26,  66, -13,  27, -55,  73,  12,   0])

In [168]:
arr1*arr2

array([3780, 1275, 3927, 2880, 5964, 2170, 1896, 1020, 1260,  225])

In [169]:
arr1/arr2

array([0.77142857, 4.41176471, 0.66233766, 3.2       , 0.8452381 ,
       1.77142857, 0.30379747, 7.08333333, 1.4       , 1.        ])

### scaler value

In [170]:
arr1*100

array([5400, 7500, 5100, 9600, 7100, 6200, 2400, 8500, 4200, 1500])

In [171]:
arr1+5

array([ 59,  80,  56, 101,  76,  67,  29,  90,  47,  20])

In [173]:
arr1.sum()

575

In [174]:
np.exp(arr1)

array([2.83075330e+23, 3.73324200e+32, 1.40934908e+22, 4.92345829e+41,
       6.83767123e+30, 8.43835667e+26, 2.64891221e+10, 8.22301271e+36,
       1.73927494e+18, 3.26901737e+06])

In [175]:
np.sin(arr1)

array([-0.55878905, -0.38778164,  0.67022918,  0.98358775,  0.95105465,
       -0.7391807 , -0.90557836, -0.17607562, -0.91652155,  0.65028784])

In [176]:
np.cos(arr1)

array([-0.82930983,  0.92175127,  0.7421542 , -0.18043045, -0.30902273,
        0.67350716,  0.42417901, -0.98437664, -0.39998531, -0.75968791])

In [177]:
np.sqrt(arr1)

array([7.34846923, 8.66025404, 7.14142843, 9.79795897, 8.42614977,
       7.87400787, 4.89897949, 9.21954446, 6.4807407 , 3.87298335])

In [181]:
b

array([[14, 40, 34, 29, 48],
       [47, 46, 45, 28, 35],
       [13, 26, 61, 43, 82],
       [24, 40, 23, 34, 40]])

In [191]:
b.sum(axis=1) # axis=1 means rows

array([165, 201, 225, 161])

In [183]:
b.sum(axis=0)# axis=0 means columns

array([ 98, 152, 163, 134, 205])

In [195]:
a=np.random.randint(20,100,(5,3))
a

array([[97, 54, 27],
       [75, 83, 58],
       [72, 27, 42],
       [73, 67, 29],
       [89, 93, 46]])

In [197]:
for row in a:
    print(row)

[97 54 27]
[75 83 58]
[72 27 42]
[73 67 29]
[89 93 46]


### argmax() , argmin()

In [204]:
a=np.random.randint(10,100,(10))
a

array([89, 80, 29, 58, 11, 90, 18, 58, 69, 57])

In [205]:
a.max()

90

In [206]:
a.argmax() # return the index of the maximum number

5

In [207]:
a.min()

11

In [208]:
a.argmin() # return the index of the minimum number

4

### reshape()

In [209]:
a=np.random.randint(10,100,(10,2))
a

array([[91, 79],
       [87, 97],
       [83, 60],
       [20, 39],
       [15, 72],
       [39, 88],
       [61, 74],
       [80, 46],
       [52, 31],
       [19, 61]])

In [210]:
a.reshape(2,10)

array([[91, 79, 87, 97, 83, 60, 20, 39, 15, 72],
       [39, 88, 61, 74, 80, 46, 52, 31, 19, 61]])

In [212]:
a.reshape(4,5)

array([[91, 79, 87, 97, 83],
       [60, 20, 39, 15, 72],
       [39, 88, 61, 74, 80],
       [46, 52, 31, 19, 61]])

In [213]:
a.reshape(5,4)

array([[91, 79, 87, 97],
       [83, 60, 20, 39],
       [15, 72, 39, 88],
       [61, 74, 80, 46],
       [52, 31, 19, 61]])

### ravel()

In [216]:
a

array([[91, 79],
       [87, 97],
       [83, 60],
       [20, 39],
       [15, 72],
       [39, 88],
       [61, 74],
       [80, 46],
       [52, 31],
       [19, 61]])

In [217]:
a.ravel()

array([91, 79, 87, 97, 83, 60, 20, 39, 15, 72, 39, 88, 61, 74, 80, 46, 52,
       31, 19, 61])

In [219]:
a.resize(2,10)
a

array([[91, 79, 87, 97, 83, 60, 20, 39, 15, 72],
       [39, 88, 61, 74, 80, 46, 52, 31, 19, 61]])

In [220]:
a.reshape(2,10)

array([[91, 79, 87, 97, 83, 60, 20, 39, 15, 72],
       [39, 88, 61, 74, 80, 46, 52, 31, 19, 61]])

In [221]:
a

array([[91, 79, 87, 97, 83, 60, 20, 39, 15, 72],
       [39, 88, 61, 74, 80, 46, 52, 31, 19, 61]])

In [229]:
np.hsplit(a,5)

[array([[91, 79],
        [39, 88]]), array([[87, 97],
        [61, 74]]), array([[83, 60],
        [80, 46]]), array([[20, 39],
        [52, 31]]), array([[15, 72],
        [19, 61]])]

In [232]:
a=np.random.randint(10,100,(10))
a

array([48, 61, 37, 88, 52, 69, 77, 43, 47, 62])

In [234]:
b=np.random.randint(10,100,(10))
b

array([87, 52, 61, 70, 42, 34, 51, 43, 27, 60])

In [238]:
np.hstack((a,b))

array([48, 61, 37, 88, 52, 69, 77, 43, 47, 62, 87, 52, 61, 70, 42, 34, 51,
       43, 27, 60])

In [244]:
a=a.reshape(2,5)
a

array([[48, 61, 37, 88, 52],
       [69, 77, 43, 47, 62]])

In [243]:
a.transpose()

array([[48, 69],
       [61, 77],
       [37, 43],
       [88, 47],
       [52, 62]])

### Ex. answer

In [247]:
c=['GBR','China','RUS','US','KOR','JPN','GER']
cg=[29,38,24,46,13,7,11]
cs=[17,28,25,28,8,14,11]
cb=[19,22,32,29,7,17,14]


In [248]:
import numpy as np

In [250]:
c_array=np.array(c)
print(c_array)
cg_array=np.array(cg)
print(cg_array)
cs_array=np.array(cs)
print(cs_array)
cb_array=np.array(cb)
print(cb_array)

['GBR' 'China' 'RUS' 'US' 'KOR' 'JPN' 'GER']
[29 38 24 46 13  7 11]
[17 28 25 28  8 14 11]
[19 22 32 29  7 17 14]


In [252]:
c_array[cg_array.argmax()]

'US'

In [254]:
c_array[cg_array>20]

array(['GBR', 'China', 'RUS', 'US'], dtype='<U5')

In [255]:
n=len(c_array)
for i in range(n):
    
    print("total medal for",c_array[i],":",cg_array[i]+cs_array[i]+cb_array[i])

total medal for GBR : 65
total medal for China : 88
total medal for RUS : 81
total medal for US : 103
total medal for KOR : 28
total medal for JPN : 38
total medal for GER : 36


In [258]:
medals=np.hstack((cg_array,cs_array,cb_array))
medals

array([29, 38, 24, 46, 13,  7, 11, 17, 28, 25, 28,  8, 14, 11, 19, 22, 32,
       29,  7, 17, 14])

In [260]:
medals.reshape((3,7))

array([[29, 38, 24, 46, 13,  7, 11],
       [17, 28, 25, 28,  8, 14, 11],
       [19, 22, 32, 29,  7, 17, 14]])

In [262]:
medals.sum(axis=0)

array([ 65,  88,  81, 103,  28,  38,  36])

In [263]:
n=len(c_array)
for i in range(n):
    
    print("total medal for",c_array[i],":",cg_array[i])

total medal for GBR : 29
total medal for China : 38
total medal for RUS : 24
total medal for US : 46
total medal for KOR : 13
total medal for JPN : 7
total medal for GER : 11
