In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv(r"C:\Users\etisalat\Desktop\Etisalat Main Folder\Training Materials\Machine Learning\Machine Learning using microsoft Azure\doc\Bank-Telemarketing.csv")

In [3]:
data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [30]:
data.shape

(41188, 21)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null object
dtypes: float64(5), int64(5), object(11)
memory usa

In [6]:
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
encoder=LabelEncoder()

In [11]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [12]:
columns=[ 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'poutcome', 'y']

for i in columns:
    data[i]=encoder.fit_transform(data[i])

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null int32
marital           41188 non-null int32
education         41188 non-null int32
default           41188 non-null int32
housing           41188 non-null int32
loan              41188 non-null int32
contact           41188 non-null int32
month             41188 non-null int32
day_of_week       41188 non-null int32
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null int32
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null int32
dtypes: float64(5), int32(11), int64(5)
memory usage: 4.9 MB


In [14]:
data.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          0        0        0     0        1      6   
1   57    7        1          3        1        0     0        1      6   
2   37    7        1          3        0        2     0        1      6   
3   40    0        1          1        0        0     0        1      6   
4   56    7        1          3        0        0     2        1      6   

   day_of_week ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1 ...         1    999         0         1           1.1   
1            1 ...         1    999         0         1           1.1   
2            1 ...         1    999         0         1           1.1   
3            1 ...         1    999         0         1           1.1   
4            1 ...         1    999         0         1           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0  

[5 rows x 21 columns]

In [16]:
data.corr()["y"]

age               0.030399
job               0.025122
marital           0.046203
education         0.057799
default          -0.099352
housing           0.011552
loan             -0.004909
contact          -0.144773
month            -0.006065
day_of_week       0.015967
duration          0.405274
campaign         -0.066357
pdays            -0.324914
previous          0.230181
poutcome          0.129789
emp.var.rate     -0.298334
cons.price.idx   -0.136211
cons.conf.idx     0.054878
euribor3m        -0.307771
nr.employed      -0.354678
y                 1.000000
Name: y, dtype: float64

### devide (x) and (y)

In [18]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

### normalization

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler=MinMaxScaler()

In [22]:
data_sc=scaler.fit_transform(x)

In [26]:
data_sc

array([[0.48148148, 0.27272727, 0.33333333, ..., 0.60251046, 0.95737928,
        0.85973535],
       [0.49382716, 0.63636364, 0.33333333, ..., 0.60251046, 0.95737928,
        0.85973535],
       [0.24691358, 0.63636364, 0.33333333, ..., 0.60251046, 0.95737928,
        0.85973535],
       ...,
       [0.48148148, 0.45454545, 0.33333333, ..., 0.        , 0.08932215,
        0.        ],
       [0.33333333, 0.81818182, 0.33333333, ..., 0.        , 0.08932215,
        0.        ],
       [0.7037037 , 0.45454545, 0.33333333, ..., 0.        , 0.08932215,
        0.        ]])

In [24]:
data_sc.max()

1.0

In [25]:
data_sc.min()

0.0

### split the data into (training) and (testing)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
xtrain,xtest,ytrain,ytest=train_test_split(data_sc,y,test_size=0.3,random_state=123)

In [31]:
xtrain.shape

(28831, 20)

In [32]:
xtest.shape

(12357, 20)

### creating logistic regression model

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
model=LogisticRegression()

In [35]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [37]:
ypred=model.predict(xtest)

In [41]:
model.score(xtest,ytest)

0.9116290361738286

### another way to calculate the ACC

In [44]:
from sklearn.metrics import accuracy_score ,confusion_matrix

In [43]:
accuracy_score(ytest,ypred)

0.9116290361738286

In [45]:
confusion_matrix(ytest,ypred)

array([[10726,   235],
       [  857,   539]], dtype=int64)

#### the Acc equation

In [48]:
acc=(10726+539)/(539+235+857+10726)
acc

0.9116290361738286

### changing the threshold for the final output

In [50]:
ypred[0:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [62]:
model.predict_proba(xtest)[:20,:]

array([[0.98116219, 0.01883781],
       [0.78843825, 0.21156175],
       [0.97273976, 0.02726024],
       [0.98387092, 0.01612908],
       [0.86231497, 0.13768503],
       [0.98427785, 0.01572215],
       [0.96059228, 0.03940772],
       [0.9786971 , 0.0213029 ],
       [0.04788798, 0.95211202],
       [0.97301324, 0.02698676],
       [0.95175422, 0.04824578],
       [0.96430302, 0.03569698],
       [0.22270215, 0.77729785],
       [0.96629406, 0.03370594],
       [0.97059707, 0.02940293],
       [0.98745623, 0.01254377],
       [0.95912103, 0.04087897],
       [0.91500315, 0.08499685],
       [0.99140599, 0.00859401],
       [0.82439321, 0.17560679]])

In [71]:
proba=model.predict_proba(xtest)[:,1]

In [72]:
p=[]
for i in proba:
    if i >0.8:
        p.append(1)
    else:
        p.append(0)

In [73]:
p

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,


In [74]:
p_array=np.array(p)

In [75]:
p_array

array([0, 0, 0, ..., 0, 0, 0])

In [82]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [85]:
final=pd.DataFrame(xtest,columns=[['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed']])

In [87]:
final["pred"]=p_array

In [88]:
final

age       job   marital education default housing loan contact  \
0      0.308642  0.636364  0.333333  0.428571     0.0     0.0  0.0     1.0   
1      0.246914  0.090909  0.333333  0.142857     0.0     0.5  0.5     0.0   
2      0.296296  0.090909  0.333333  0.142857     0.5     0.0  0.0     1.0   
3      0.308642  0.000000  0.333333  0.857143     0.5     1.0  0.0     1.0   
4      0.481481  0.181818  0.333333  0.428571     0.0     1.0  0.0     0.0   
5      0.481481  0.181818  0.333333  0.857143     0.0     1.0  1.0     1.0   
6      0.209877  0.000000  0.333333  0.857143     0.0     0.0  0.0     1.0   
7      0.135802  0.090909  0.666667  0.285714     0.0     1.0  0.0     1.0   
8      0.185185  0.818182  0.333333  0.714286     0.0     0.0  0.0     1.0   
9      0.172840  0.636364  0.666667  0.428571     0.0     0.0  0.0     0.0   
10     0.222222  0.000000  0.333333  0.428571     0.0     1.0  0.0     0.0   
11     0.271605  0.000000  0.666667  0.857143     0.0     1.0  1.0     0.0   
12     0.135802  0.727273  0.666667  0.428571     0.0     1.0  0.0     0.0   
13     0.296296  0.818182  0.333333  0.857143     0.0     1.0  0.0     0.0   
14     0.148148  0.818182  0.666667  0.714286     0.0     0.0  0.0     0.0   
15     0.271605  0.545455  0.333333  0.000000     0.5     0.0  0.0     0.0   
16     0.259259  0.090909  0.333333  0.000000     0.5     1.0  0.0     0.0   
17     0.382716  0.000000  0.666667  0.857143     0.0     0.0  0.0     0.0   
18     0.518519  0.000000  0.333333  0.142857     0.0     1.0  0.0     1.0   
19     0.518519  0.454545  0.333333  0.000000     0.0     1.0  0.0     1.0   
20     0.296296  0.090909  0.333333  1.000000     0.0     1.0  0.0     0.0   
21     0.493827  0.000000  0.333333  0.714286     0.0     0.5  0.5     0.0   
22     0.283951  0.818182  0.333333  0.428571     0.0     1.0  0.0     1.0   
23     0.074074  0.818182  0.666667  0.428571     0.0     0.0  1.0     0.0   
24     0.296296  0.090909  0.333333  0.000000     0.5     0.5  0.5     0.0   
25     0.456790  0.909091  0.333333  0.285714     0.0     0.0  0.0     1.0   
26     0.197531  0.000000  0.333333  0.714286     0.0     0.0  0.0     1.0   
27     0.456790  0.363636  0.000000  0.857143     0.0     1.0  0.0     1.0   
28     0.320988  0.000000  0.000000  0.285714     0.0     1.0  0.0     0.0   
29     0.382716  0.000000  0.333333  0.428571     0.0     0.0  0.0     1.0   
...         ...       ...       ...       ...     ...     ...  ...     ...   
12327  0.234568  0.000000  0.666667  0.857143     0.0     0.0  0.0     1.0   
12328  0.246914  0.000000  0.333333  0.428571     0.0     1.0  0.0     1.0   
12329  0.148148  0.000000  0.333333  0.857143     0.0     0.0  0.0     0.0   
12330  0.172840  0.090909  0.333333  0.285714     0.0     0.0  0.0     1.0   
12331  0.469136  0.818182  0.000000  0.714286     0.0     0.0  1.0     0.0   
12332  0.209877  0.545455  0.666667  0.857143     0.0     1.0  0.0     0.0   
12333  0.086420  0.818182  0.666667  0.714286     0.0     1.0  0.0     1.0   
12334  0.123457  0.000000  0.666667  0.428571     0.5     1.0  0.0     1.0   
12335  0.259259  0.000000  0.333333  0.428571     0.0     0.0  0.0     0.0   
12336  0.135802  0.363636  0.666667  0.857143     0.0     1.0  0.0     0.0   
12337  0.419753  0.181818  0.000000  0.857143     0.5     0.0  0.0     1.0   
12338  0.222222  0.818182  0.333333  0.714286     0.0     1.0  0.0     0.0   
12339  0.098765  0.818182  0.333333  0.714286     0.0     0.0  0.0     0.0   
12340  0.419753  0.000000  0.666667  0.857143     0.0     0.0  0.0     1.0   
12341  0.148148  0.000000  0.333333  0.285714     0.0     0.0  0.0     0.0   
12342  0.382716  0.818182  0.000000  0.714286     0.0     0.0  0.0     0.0   
12343  0.333333  0.000000  0.333333  0.428571     0.0     1.0  0.0     0.0   
12344  0.320988  0.636364  0.000000  0.428571     0.0     1.0  0.0     1.0   
12345  0.530864  0.090909  0.333333  0.285714     0.5     0.0  0.0     1.0   
12346  0.185185  0.363636  0.66666