In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
data=pd.read_csv(r"C:\Users\etisalat\Downloads\Bank_churn_modelling.csv")

In [9]:
data.shape

(10000, 14)

In [10]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [13]:
data.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [15]:
data.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [17]:
data.drop_duplicates(inplace=True)

In [18]:
data.shape

(10000, 11)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [24]:
enc=LabelEncoder()
data["Geography"]=enc.fit_transform(data["Geography"])
data["Gender"]=enc.fit_transform(data["Gender"])

In [26]:
data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [27]:
data.corr()

CreditScore  Geography    Gender       Age    Tenure  \
CreditScore         1.000000   0.007888 -0.002857 -0.003965  0.000842   
Geography           0.007888   1.000000  0.004719  0.022812  0.003739   
Gender             -0.002857   0.004719  1.000000 -0.027544  0.014733   
Age                -0.003965   0.022812 -0.027544  1.000000 -0.009997   
Tenure              0.000842   0.003739  0.014733 -0.009997  1.000000   
Balance             0.006268   0.069408  0.012087  0.028308 -0.012254   
NumOfProducts       0.012238   0.003972 -0.021859 -0.030680  0.013444   
HasCrCard          -0.005458  -0.008523  0.005766 -0.011721  0.022583   
IsActiveMember      0.025651   0.006724  0.022544  0.085472 -0.028362   
EstimatedSalary    -0.001384  -0.001369 -0.008112 -0.007201  0.007784   
Exited             -0.027094   0.035943 -0.106512  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Geography        0.069408       0.003972  -0.008523        0.006724   
Gender           0.012087      -0.021859   0.005766        0.022544   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
CreditScore            -0.001384 -0.027094  
Geography              -0.001369  0.035943  
Gender                 -0.008112 -0.106512  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

### split (x) and (y) columns

In [29]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [30]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [31]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
scaler=MinMaxScaler()

In [34]:
x_sc=scaler.fit_transform(x)

In [36]:
x_sc.max()

1.0000000000000002

In [37]:
x_sc.min()

0.0

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
xtrain,xtest,ytrain,ytest=train_test_split(x_sc,y,test_size=0.3,random_state=123)

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
model=LogisticRegression()

In [46]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [47]:
model.score(xtest,ytest)

0.81

In [49]:
ypred=model.predict(xtest)

In [50]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(ytest,ypred)

array([[2341,   54],
       [ 516,   89]], dtype=int64)

### Note:


# preprocessing
#from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.preprocessing import PolynomialFeatures
#from sklearn.preprocessing import OneHotEncoder

#from sklearn.model_selection import train_test_split

# Regression algorithm
#from sklearn.linear_model import LinearRegression

#from sklearn.tree import DecisionTreeRegressor
#from sklearn.ensemble import RandomForestRegressor

# Classification algorithms
#from sklearn.linear_model import LogisticRegression

### saving the model - method 1

In [63]:
import pickle

In [74]:
pickle.dump(model,open("t.sav","wb"))

In [76]:
m=pickle.load(open("t.sav","rb"))

In [77]:
m.score(xtest,ytest)

0.81

### saving the model method 2

In [78]:
import joblib

In [79]:
joblib.dump(model,"test.pkl")

['test.pkl']

In [81]:
model2=joblib.load("test.pkl")

In [83]:
model2.score(xtest,ytest)

0.81

### saving the scaler

In [84]:
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']