In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv(r"C:\Users\etisalat\Downloads\02Students.csv")

In [3]:
data

Hours  sHours  Marks
0       0       6     34
1       1       7     36
2       1       6     33
3       1       8     39
4       1       8     42
5       2       8     45
6       2       6     38
7       3       6     45
8       3       7     53
9       3       7     46
10      3       8     56
11      4       8     59
12      4       7     55
13      4       7     56
14      5       8     72
15      5       6     59
16      6       6     62
17      6       7     71
18      7       8     78
19      7       8     88
20      7       6     61
21      7       6     74
22      8       7     71
23      8       8     89
24      9       8     82
25      9       5     67
26      9       8     89
27     10       8     81
28     10       8     82
29     11       7     79

### split the data into x and y

In [4]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [5]:
x

array([[ 0,  6],
       [ 1,  7],
       [ 1,  6],
       [ 1,  8],
       [ 1,  8],
       [ 2,  8],
       [ 2,  6],
       [ 3,  6],
       [ 3,  7],
       [ 3,  7],
       [ 3,  8],
       [ 4,  8],
       [ 4,  7],
       [ 4,  7],
       [ 5,  8],
       [ 5,  6],
       [ 6,  6],
       [ 6,  7],
       [ 7,  8],
       [ 7,  8],
       [ 7,  6],
       [ 7,  6],
       [ 8,  7],
       [ 8,  8],
       [ 9,  8],
       [ 9,  5],
       [ 9,  8],
       [10,  8],
       [10,  8],
       [11,  7]], dtype=int64)

In [6]:
y

array([34, 36, 33, 39, 42, 45, 38, 45, 53, 46, 56, 59, 55, 56, 72, 59, 62,
       71, 78, 88, 61, 74, 71, 89, 82, 67, 89, 81, 82, 79], dtype=int64)

### splitting the data into (training ) and (testing)

In [7]:
from sklearn.model_selection import train_test_split

In [32]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.4,random_state=123)

In [33]:
xtrain

array([[ 1,  8],
       [ 9,  8],
       [ 6,  6],
       [ 5,  8],
       [ 7,  6],
       [ 3,  7],
       [ 5,  6],
       [ 9,  5],
       [ 0,  6],
       [ 1,  7],
       [ 8,  7],
       [ 3,  8],
       [ 7,  8],
       [ 6,  7],
       [ 2,  6],
       [10,  8],
       [ 1,  6],
       [ 4,  7]], dtype=int64)

In [34]:
xtest

array([[ 3,  6],
       [11,  7],
       [ 2,  8],
       [ 9,  8],
       [ 3,  7],
       [10,  8],
       [ 4,  7],
       [ 7,  6],
       [ 4,  8],
       [ 8,  8],
       [ 7,  8],
       [ 1,  8]], dtype=int64)

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
model=LinearRegression()

In [37]:
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [38]:
model.predict(xtest)

array([44.58075704, 89.41740173, 50.71426736, 85.11299991, 50.10456453,
       90.02710456, 55.01866918, 64.23717564, 60.54247666, 80.19889526,
       75.28479061, 45.80016271])

In [39]:
model.intercept_

-3.304401815534817

In [40]:
model.coef_

array([4.91410465, 5.52380748])

In [41]:
# y= x1m1 + x2m2 + b     

In [42]:
model.score(xtest,ytest)

0.8717404199841874

In [43]:
model.score(xtrain,ytrain)

0.9098211975917466