In [1]:
import tensorflow

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Salary_Data (2).csv to Salary_Data (2) (4).csv


In [5]:
import io
data=pd.read_csv(io.StringIO(uploaded['Salary_Data (2).csv'].decode('utf-8')))
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [6]:
data.shape

(30, 2)

In [7]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [8]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [9]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler=MinMaxScaler()

In [13]:
scaler.fit(x)

MinMaxScaler()

In [14]:
x_scaled=scaler.transform(x)

In [15]:
x_scaled

array([[0.        ],
       [0.0212766 ],
       [0.04255319],
       [0.09574468],
       [0.11702128],
       [0.19148936],
       [0.20212766],
       [0.22340426],
       [0.22340426],
       [0.27659574],
       [0.29787234],
       [0.30851064],
       [0.30851064],
       [0.31914894],
       [0.36170213],
       [0.40425532],
       [0.42553191],
       [0.44680851],
       [0.5106383 ],
       [0.5212766 ],
       [0.60638298],
       [0.63829787],
       [0.72340426],
       [0.75531915],
       [0.80851064],
       [0.84042553],
       [0.89361702],
       [0.90425532],
       [0.9787234 ],
       [1.        ]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled, y, test_size = 0.3, random_state = 345)

In [17]:
X_train.shape

(21, 1)

In [18]:
X_test.shape

(9, 1)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
model=Sequential()
model.add(Dense(4,activation="relu"))
model.add(Dense(8,activation="relu"))  
model.add(Dense(1))

In [21]:
from keras import optimizers

In [22]:
model.compile(optimizer="rmsprop" ,loss="mse")

In [23]:
model.fit(X_train,y_train,epochs=20,batch_size=2)

Epoch 1/20
11/11 [==============================] - 3s 16ms/step - loss: 6010995712.0000
Epoch 2/20
11/11 [==============================] - 0s 25ms/step - loss: 6010981888.0000
Epoch 3/20
11/11 [==============================] - 0s 21ms/step - loss: 6010970624.0000
Epoch 4/20
11/11 [==============================] - 0s 20ms/step - loss: 6010958848.0000
Epoch 5/20
11/11 [==============================] - 0s 14ms/step - loss: 6010948096.0000
Epoch 6/20
11/11 [==============================] - 0s 15ms/step - loss: 6010935808.0000
Epoch 7/20
11/11 [==============================] - 0s 20ms/step - loss: 6010925056.0000
Epoch 8/20
11/11 [==============================] - 0s 15ms/step - loss: 6010911232.0000
Epoch 9/20
11/11 [==============================] - 0s 9ms/step - loss: 6010897920.0000
Epoch 10/20
11/11 [==============================] - 0s 7ms/step - loss: 6010884608.0000
Epoch 11/20
11/11 [==============================] - 0s 8ms/step - loss: 6010871296.0000
Epoch 12/20
11/11 [===

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 8         
                                                                 
 dense_1 (Dense)             (None, 8)                 40        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.history.history["loss"]

[6010995712.0,
 6010981888.0,
 6010970624.0,
 6010958848.0,
 6010948096.0,
 6010935808.0,
 6010925056.0,
 6010911232.0,
 6010897920.0,
 6010884608.0,
 6010871296.0,
 6010859008.0,
 6010845184.0,
 6010829824.0,
 6010814976.0,
 6010800128.0,
 6010784256.0,
 6010767872.0,
 6010751488.0,
 6010735104.0]

In [26]:
%matplotlib

Using matplotlib backend: agg


In [27]:
import matplotlib.pyplot as plt
plt.plot(model.history.history["loss"],marker="o")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.show()

In [28]:
ypred=model.predict(X_test)

In [29]:
from sklearn.metrics import explained_variance_score

In [30]:
explained_variance_score(y_test,ypred)

3.5796568970458686e-05

In [31]:
y_test

array([116969.,  37731., 113812., 112635.,  83088.,  54445.,  91738.,
        56642.,  81363.])

In [32]:
ypred

array([[2.6572332],
       [1.2340242],
       [2.425962 ],
       [2.6750236],
       [1.9100484],
       [1.536456 ],
       [2.1769001],
       [1.4830858],
       [2.0167892]], dtype=float32)